### ISSUE TITLE
ao spawn is passing undefined as module

### ISSUE THREAD

**Issue by av1ctor** [permaweb/ao#1002]
Version 0.1.3

When running spawn, the env var MODULE_TX is passed as undefined to the Docker container.

Maybe at https://github.com/permaweb/ao/blob/d3704747e08a2bc53c854578cc30ad33d0ea2bfb/dev-cli/src/commands/spawn.js#L19 the "source" field should be actually "module" (the ao CLI's argument name)?

> ao spawn --module SOME_MODULE_TX -w ../arweave-keyfile.json 

> node:internal/process/promises:288
>             triggerUncaughtException(err, true /* fromPromise */);
>             ^

> Error: Invalid Arguments '0': Required.
>     at errFrom (file:///opt/node/node_modules/@permaweb/aoconnect/dist/index.js:383:9)
>     at file:///opt/node/node_modules/@permaweb/aoconnect/dist/index.js:17:18
>     at file:///opt/node/node_modules/@permaweb/aoconnect/dist/index.js:17:14
>     at file:///opt/node/node_modules/@permaweb/aoconnect/dist/index.js:17:14ZodError: [
>   {
>     "code": "invalid_arguments",
>     "argumentsError": {
>       "issues": [
>         {
>           "code": "invalid_type",
>           "expected": "string",
>           "received": "undefined",
>           "path": [
>             0
>           ],
>           "message": "Required"
>         }
>       ],
>       "name": "ZodError"
>     },
>     "path": [],
>     "message": "Invalid function arguments"
>   }
> ]
>     at file:///opt/node/node_modules/zod/lib/index.mjs:3166:31
>     at Object.fork (file:///opt/node/node_modules/@permaweb/aoconnect/dist/index.js:39:17)
>     at file:///opt/node/node_modules/@permaweb/aoconnect/dist/index.js:21:61
> 
> Node.js v18.17.0

**Comment by TillaTheHun0** [comment]
We'll need to look into this. Most ao builders are using `aos` to spawn their own modules that extend `aos`.

You can also use [`aoconnect`](https://github.com/permaweb/ao/tree/main/connect#spawn) to spawn a process from a module.

**Comment by av1ctor** [comment]
@TillaTheHun0, thanks again! 

I added the PR #1005 to fix this issue.
