### ISSUE TITLE
call createDataItemSigner error in next.js

### ISSUE THREAD

**Issue by pChao3** [permaweb/ao#1052]
Hello, when I used next.js and installed aoconnect, an error occurred when I tried to sign message using createDataItemSigner.
TypeError: arweaveWallet.signDataItem is not a function
    at signer (browser.js:11951:38)
    at eval (browser.js:8855:39)

**Comment by pChao3** [comment]
What is the cause of this?  and how to fix it ? Thank you

**Comment by pChao3** [comment]
Hi, @TillaTheHun0, I just want to sign with my local key file, just like running in a node environment, and I don't want to sign through the browser plug-in of ar wallet. Is it not feasible to directly import createDataItemSigner and then pass in the key file in a browser environment? Do I have to use an arconnect extension?
