### ISSUE TITLE
[BUG] - `ao build` fails

### ISSUE THREAD

**Issue by dtfiedler** [permaweb/ao#688]
I've installed `ao` via

```shell
curl -fsSL https://install_ao.g8way.io | bash
export AO_INSTALL=~/.ao
export PATH="$AO_INSTALL/bin:$PATH"
```
and the version is 
```shell
> ao --version                                                                                                            7s
ao 0.0.54
```

When running `ao build` I get `list index out of range` error:
```shell
> ao build                                                                                                           
 1m 23s
Traceback (most recent call last):
  File "/usr/local/bin/emcc-lua", line 195, in <module>
    main()
  File "/usr/local/bin/emcc-lua", line 138, in main
    if lines[0].find("\xef\xbb\xbf") != -1:
IndexError: list index out of range
```

**Comment by dtfiedler** [comment]
Moving to the relevant directory resolved

```
> cd contract/
> ao build
> ao build
emcc: warning: -sMEMORY64 is still experimental. Many features may not work. [-Wexperimental]
cache:INFO: generating system asset: symbol_lists/90be13d5bafb3254bd351cb6d04d5e6d75f87d33.json... (this will be cached in "/emsdk/upstream/emscripten/cache/symbol_lists/90be13d5bafb3254bd351cb6d04d5e6d75f87d33.json" for subsequent builds)
cache:INFO:  - ok
```
So this is more of a feature request to specify the directory you want to build
```shell
> ao build ./contract
```
