### ISSUE TITLE
@permaweb/aoconnect fails to send message when using Sveltekit.

### ISSUE THREAD

**Issue by saklani** [permaweb/ao#715]
On the server side, I am trying to load some data from an ao contract. However, it fails with the following error.

The code below is what I have written -
```ts 
//+page.server.ts
import { PRIVATE_KEY } from '$env/static/private';
import {
  createDataItemSigner,
  result as readResult,
  message as sendMessage,
} from "@permaweb/aoconnect";


const process = "qAbHIghbi7lb0Y8KdZr8q9dvH8xwXpawCXgGSD8OpJk"

export type Staker = { id: string; url: string; reputation: string };
export type StakersArgs = { privateKey: any; }
export type StakersResponse = Promise<Staker[]>

// Get list of all Stakers
export async function Stakers({ privateKey }: StakersArgs): StakersResponse {
  const signer = createDataItemSigner(privateKey);
  const message = await sendMessage({
    process,
    data: "1984",
    tags: [
      { name: "Action", value: "Stakers" },
    ],
    signer,
  });
  const result = await readResult({
    process,
    message,
  });
  if (result.Error) {
    throw new Error(result.Error);
  }
  return result.Messages[0].Data;
}
export async function load({ }) {
  const stakers = await Stakers({privateKey: PRIVATE_KEY})
	return {
    stakers: stakers,
  };
}
```

This is the error I hit
```sh
TypeError: Cannot read properties of undefined (reading 'toString')
    at toBase64 (/Users/apple/Development/liteseed/debug/aoconnect-ssr/node_modules/base64url/dist/base64url.js:17:27)
    at Function.toBuffer (/Users/apple/Development/liteseed/debug/aoconnect-ssr/node_modules/base64url/dist/base64url.js:29:24)
    at get publicKey [as publicKey] (/Users/apple/Development/liteseed/debug/aoconnect-ssr/node_modules/warp-arbundles/build/node/cjs/src/signing/chains/ArweaveSigner.js:27:36)
    at createData (/Users/apple/Development/liteseed/debug/aoconnect-ssr/node_modules/warp-arbundles/build/node/cjs/src/ar-data-create.js:15:27)
    at signer (file:///Users/apple/Development/liteseed/debug/aoconnect-ssr/node_modules/@permaweb/aoconnect/dist/index.js:1074:22)
    at file:///Users/apple/Development/liteseed/debug/aoconnect-ssr/node_modules/zod/lib/index.mjs:3351:46
```

**Comment by TillaTheHun0** [comment]
Hey @saklani. Thanks for filing the issue.

What are you passing to `createDataItemSigner` -- what is `privateKey`? When using `aoconnect` in the browser, `createDataItem` signers expects an instance of `arweaveWallet`. See [here](https://github.com/permaweb/ao/tree/main/connect#createdataitemsigner)

**Comment by TillaTheHun0** [comment]
Closing for now, as I haven't heard back from the filer. Happy to reopen if more information is provided.
