### ISSUE TITLE
Inserting too many blocks into SQLite cache using single prepared statement causes error

### ISSUE THREAD

**Issue by TillaTheHun0** [permaweb/ao#850]
## Background

The CU, when generating Cron messages, will query block metadata from Arweave gateways, and then cache them in it's own internal SQLite database. It does so by fetching range of blocks, as much as the gateway will allow in a single page, gather them all and then insert them into the database as single insert

## Problem

If the range of blocks retrieved is sufficient, this can cause the prepared statement to fail, due to too many variables:

```
An error bubbled to the top handler. Formatting and relaying to client: SqliteError: too many SQL variables
    at Database.prepare (ao/servers/cu/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at Object.run (file:///ao/servers/cu/src/domain/client/sqlite.js:110:44)
    at file:////ao/servers/cu/src/domain/client/ao-block.js:48:39
    at Object.fork (file:///ao/servers/cu/node_modules/hyper-async/dist/index.js:30:17)
    at file:///ao/servers/cu/node_modules/hyper-async/dist/index.js:12:61
    at file:///ao/servers/cu/node_modules/hyper-async/dist/index.js:5:53
    at file:///ao/servers/cu/node_modules/hyper-async/dist/index.js:26:37
    at file:///ao/servers/cu/node_modules/hyper-async/dist/index.js:5:36
    at file:///ao/servers/cu/node_modules/hyper-async/dist/index.js:12:38
    at file:///ao/servers/cu/node_modules/hyper-async/dist/index.js:4:53 {
  code: 'SQLITE_ERROR'
}
```

## Solution

Break up the operation into multiple operations, where each operation contains an acceptable number of variables in each prepared statement.

**Comment by TillaTheHun0** [comment]
Closed by 8fc40dc
